name: Observatory Scan Action
description: An action to run the Mozilla Observatory scan and return results.
author: https://opslayer.com/
inputs:
  url:
    description: "The URL for the observatory scan."
    required: true

runs:
  using: "composite"
  steps:
    - name: 🤘 Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - name: Bun version
      run: bun --version
      shell: bash

    - name: 💻 Run Observatory script
      run: bun index.ts
      shell: bash

    - name: Print observatory.md
      run: cat observatory.md
      shell: bash

    - name: Read observatory.md
      id: read-file
      uses: jaywcjlove/github-action-read-file@main
      with:
        localfile: observatory.md

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          # Mozilla Observatory Scan Results
          ${{ steps.read-file.outputs.content }}
